### ISSUE TITLE
Sidfoten är för långt ner

### ISSUE THREAD

**Issue by marcusnaslund** [imintsystems/imint.se#134]
På korta sidor hamnar sidfoten för långt ner, så även om innehållet är jättekort måste man scrolla för att se den. Till exempel: http://imint.se/invest/kalender/ och http://imint.se/om/kontakt/

Samtidigt ser det skumt ut med bakgrundsfärgen

Liknande exempel på vidhance.com: http://vidhance.com/newspost/CEO-interviewd-by-Breakit/

**Comment by simonmika** [comment]
@jonathanudd: Kan du titta på det?

**Comment by jonathanudd** [comment]
Ja.

**Comment by marcusnaslund** [comment]
Verkar vara löst.
