### ISSUE TITLE
"gatuvy" button

### ISSUE THREAD

**Issue by ericleimar** [imintsystems/imint.se#32]
Is there supposed to be a picture or a link to Google street view? At present there's only a small text box.
imint.se/om/adress

**Comment by marcusnaslund** [comment]
Det bör vara JPG och inte jpg i filnamnet i `adress.md`. @simonmika

**Comment by marcusnaslund** [comment]
Fixat

**Comment by davidhesselbom** [comment]
![gatubild](https://cloud.githubusercontent.com/assets/4319680/10564181/2c745274-75aa-11e5-99e7-91b1a83b8f7c.png)
