### ISSUE TITLE
Mobilt: Inte självklart hur man kommer in på "Investor relations" eller "Om"

### ISSUE THREAD

**Issue by marcusnaslund** [imintsystems/imint.se#41]

**Comment by jonathanudd** [comment]
Det går om man trycker två gånger på dom i menyn. Alltså första gången expanderas undermenyn och andra gången går man faktiskt till sidan.

Det är möjligt att detta inte är det mest naturliga sättet att göra de på och det kanske borde ändras.
- Ett förslag är att dom menylänkar som har undermeny inte går någonstans och att man istället har en länk i undermenyn som går till sidan istället.
- Ett annat förslag är att man har allting expanderat från början på mobil versionen.

**Comment by marcusnaslund** [comment]
Jag är ingen expert på HCI men tycker definitivt att det är oklart hur det går till och att alternativ 2 inte löser problemet.
Jag röstar på alternativ 1.
Vad säger du @simonmika ?

**Comment by simonmika** [comment]
Kan man inte visa sidan _och_ expandera undermenyn vid första tap?

**Comment by jonathanudd** [comment]
Menyn är numera expanderad från början när man visar den på mobiler.

**Comment by marcusnaslund** [comment]
Bättre! Den är dock fortfarande för smal, se #40

**Comment by simonmika** [comment]
Därmed är denna avslutad.
