### ISSUE TITLE
citat.md har en tom titel.

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#46]
`title = ""`

**Comment by marcusnaslund** [comment]
Det är ju bara en del av förstasidan, så den behöver ju ingen titel, eller?

**Comment by davidhesselbom** [comment]
Okej, men varför har den i så fall en `title` i sin header?

**Comment by marcusnaslund** [comment]
Låter @jonathanudd svara på det. Måste en `title`-tag finnas?

**Comment by jonathanudd** [comment]
Om man läser [här](http://gohugo.io/content/front-matter/) så krävs title men också en del saker vi inte har i våran metadata. Men vad jag har märkt så fungerar allt bra ändå så jag skulle säga att det inte behövs en `title`-tag om den ändå är tom.

**Comment by davidhesselbom** [comment]
Flera av de andra delarna saknar `title` helt och hållet, så det verkar ju inte vara något problem att ta bort den. Just den här sticker ut för att den har en sån, men den är tom.

**Comment by marcusnaslund** [comment]
Tog bort den i #59
