### ISSUE TITLE
telefon.md

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#50]
`möjligheten att fotografera med marknadsledande telefoner ligger nu nära professionell nivå.`

Syftningsfel. Möjligheten ligger inte nära professionell nivå, fotografierna gör det. Kommer tyvärr inte på hur jag ska skriva om det...

**Comment by marcusnaslund** [comment]
`nivån på foton från marknadsledande telefoner kan nu komma nära professionell nivå`?
