### ISSUE TITLE
undervatten.md

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#51]
- `minskar den nödvändiga komplexiteten hos den utsatta hårdvaran`

Heter det verkligen "utsatt hårdvara" här?

**Comment by marcusnaslund** [comment]
Det är ju just hårdvaran som är utsatt i krävande miljöer. Hur menar du?

**Comment by davidhesselbom** [comment]
Betyder "utsatt" "påfrestad" eller "placerad"? Jag vill undvika att det låter som att VIdhance är påfrestande för hårdvaran. Just nu går det lätt att tolka texten som att hårdvaran är "utsatt för Vidhance" och det låter inte så positivt.

**Comment by marcusnaslund** [comment]
Haha :) "hos den redan påfrestade hårdvaran" kanske?
