### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#52]
- `#` motsvarar `<H1>`. Det ska väl aldrig finnas mer än 1 sån tagg per sida? Eller?

- Ska det vara en tom rad efter headerns avslutande `+++`?

**Comment by marcusnaslund** [comment]
Apropå (2): Jag tycker nej. Hittar inte heller någon sida där det är så..?

**Comment by simonmika** [comment]
Det är skillnade på den `h1` som ligger i  `header` och de andra utanför. Första rubriknivån är `h1` och fler rubriknivåer är oftast inte nödvändigt.
