### ISSUE TITLE
styrelse.md

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#53]
- Bambuser nämns två gånger i Hans stycke. Vore det en idé att samla dem i samma mening?
- `Harald grundade Imint tillsammans med en studiekamrat 2008` - kan vi inte nämna denne studiekamrat vid namn här?
- "B.B.A" är en engelsk term som är ganska främmande för mig. Finns det en svensk motsvarighet, eller förväntas en person som besöker den här sidan veta vad "B.B.A" innebär? 
- `Aktiebolaget Uppsala Engineering Partner` nämns också två gånger.
- `Teleca (vVD), TAT AB (global försäljningschef och slutligen VD) och Anoto Group AB (global försäljnings- och marknadsdirektör).` - parenteserna är smidiga, men utgör ett stilbrott mot resten av artikeln.

**Comment by charlotteharnvi** [comment]
- Bambuser nämns i olika sammanhang, dels som operationell erfarenhet och dels i styrelsen, så det får nog stå så. 
- Absolut, har frågat Simon.
- B.B.A. Det är det första man får upp om man googlar, Bachelor of Business admin. 
- Tagit bort på ena stället
- Ändrat
