### ISSUE TITLE
karriar.md

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#56]
`För att säkerställa en varaktig kreativitet och engagemang när du arbetar i vårt team måste det finnas tillräckligt med tid utanför jobbet. Imint uppskattar olika typer av erfarenheter, bakgrunder och åsikter.`

Övergången mellan de här två meningarna kunde vara smidigare...

**Comment by charlotteharnvi** [comment]
Jag lade in meningen i stycket ovan istället.
