### ISSUE TITLE
Bredare avstånd mellan menyer

### ISSUE THREAD

**Issue by marcusnaslund** [imintsystems/imint.se#61]
Nu när vi dessutom har ett menyfält "investor relations" som innehåller ett mellanslag tycker jag att mellanrummet mellan menyknapparna (i sidled) borde vara liiite större.

**Comment by davidhesselbom** [comment]
Håller med. Konstigt med engelska där också.

**Comment by jonathanudd** [comment]
Will be fixed when #132 is merged.
