### ISSUE TITLE
med / utan vidhance

### ISSUE THREAD

**Issue by davidhesselbom** [imintsystems/imint.se#68]
"med vidhance"  och "utan vidhance" måste byta plats, nu står det "utan vidhance" över den halvan av videon som faktiskt är med vidhance och tvärtom...

**Comment by marcusnaslund** [comment]
Haha, har ingen av oss märkt det här förrän nu?

**Comment by davidhesselbom** [comment]
Så går det när man mergear pull requests utan mig! ;)
