### ISSUE TITLE
Lägg till en extra sidfot

### ISSUE THREAD

**Issue by jonathanudd** [imintsystems/imint.se#71]
Den ska innehålla meny till sidan, senaste nyheter och kontaktinfo.
Liknande de som fanns på gamla imint.se.

**Comment by marcusnaslund** [comment]
Yes, nyheterna ska då vara en kort rubriklista som på gamla imint.se, inte med previews som vi har på förstasidan nu.

**Comment by jonathanudd** [comment]
Fixed in #115
