### ISSUE TITLE
Nyhetsarkiv saknas

### ISSUE THREAD

**Issue by marcusnaslund** [imintsystems/imint.se#89]
Nu syns bara de fem senaste nyheterna. Det borde fungera såsom på vidhance.com

**Comment by marcusnaslund** [comment]
EDIT: Det ska inte fungera som på Vidhance utan med hjälp av paginering, se: http://gohugo.io/extras/pagination/
(Samma förändring ska implementeras på Vidhance.com)

**Comment by jonathanudd** [comment]
Fixed in #110
